# Generated by Django 3.2.10 on 2024-04-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='RHUser',
        ),
    ]
