# Generated by Django 3.2.10 on 2024-04-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_rename_user_rhuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
