# Generated by Django 3.2.10 on 2024-04-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_employe1_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projets_realises', models.IntegerField(default=0)),
                ('assiduite', models.IntegerField(default=0)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.employe1')),
            ],
        ),
        migrations.CreateModel(
            name='AppelFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.employe1')),
            ],
        ),
    ]
