# Generated by Django 3.2.10 on 2024-04-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_appelformation_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfosCandidats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('motivation', models.FileField(upload_to='cvs/')),
                ('approuve', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='demandeconge1',
            name='raison',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
