# Generated by Django 3.2.10 on 2024-04-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20240412_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconge1',
            name='raison',
            field=models.CharField(default='', max_length=100),
        ),
    ]
